import Head from "next/head";
import Banner from '../components/homepage/banner/Banner'
import GrowTraffic from '../components/homepage/growTraffic/GrowTraffic'
import Solution from '../components/homepage/solution/Solution'
import Service from '../components/homepage/service/Service'
import Workflow from "../components/homepage/workflow/Workflow";
import Clients from "../components/homepage/clients/Clients";
import Pricing from '../components/homepage/pricing/Pricing'
import Testimonial from "../components/homepage/testimonial/Testimonial";
import Blog from '../components/homepage/blog/Blog'
export default function Home() {
  return (
    <>
      <Head>
        <title>Afthonia - Business Formation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-afthonia-white.ico" />
      </Head>
      <>
        <Banner />
        <Solution />
        <Pricing />
        <Clients />
        <Testimonial />
        {/* <Service />
        <GrowTraffic />
        <Workflow />
        <Blog /> */}
      </>
    </>
  );
}
